default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: root
  host: 127.0.0.1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ichurch_development
  #host: db_painel_gestao
  port: 5432

test:
  <<: *default
  database: ichurch_test
  host: 127.0.0.1
  port: 5432


production:
  <<: *default
  host: ec2-50-19-109-120.compute-1.amazonaws.com
  port: 5432
  database: d8pj11q6j7hka4
  username: byfwhwowypfnup
  password: fc5e141ba931d5d58f6e9299760e7eeb01710e0acd53912f6f0833d0512ad56c